### ISSUE TITLE
Laboratory Work #0

### ISSUE THREAD

**Issue by BaraniukDmytro** [OS-IS/ai202-baranyuk#1]

**Comment by BaraniukDmytro** [comment]
![Снимок экрана (9988)](https://github.com/user-attachments/assets/8650c15a-d2cd-40b1-9782-70e75babbefa)
![Снимок экрана (9997)](https://github.com/user-attachments/assets/eab2add1-d444-46ad-bf17-2b83d493242f)
![Снимок экрана (9998)](https://github.com/user-attachments/assets/c8f69cd7-8172-4ad7-b276-0c837dbb248b)

**Comment by BaraniukDmytro** [comment]
![Снимок экрана (10002)](https://github.com/user-attachments/assets/20d3e560-23ad-48f9-a888-b4c0ef0f768f)
![Снимок экрана (10003)](https://github.com/user-attachments/assets/8328d77c-984d-4b7d-aa91-bb501568cefb)
![Снимок экрана (10004)](https://github.com/user-attachments/assets/5c8b7c2f-6ce7-4a93-ba94-1fec0a462b41)

**Comment by BaraniukDmytro** [comment]
![Снимок экрана (10005)](https://github.com/user-attachments/assets/a8115ac6-cdda-4b03-99a8-dd5e54ecfc1b)
![Снимок экрана (10007)](https://github.com/user-attachments/assets/2e45d2ee-bdbb-4182-b565-c359f163a547)

**Comment by oleksandrblazhko** [comment]
Рішення прийнято.
Оцінка = 5 балів.
Дякую
